### ISSUE TITLE
pyfamilyhublocal package creates error in Home Assistant

### ISSUE THREAD

**Issue by dajomas** [Klathmon/python-family-hub-local#4]
I am running Home Assistant 2024.8.3 Core on Python 3.12.5 with a fresh install in a venv.
The following versions are installed according to ```pip3 list```:
```
aiohttp                      3.10.5
python-family-hub-local      0.0.2
```
and every now and then, the following error occurs in the log file:
```
2024-08-30 10:33:31.935 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/srv/Python-3.12.5/HASS-2024.8.3/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 462, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/Python-3.12.5/HASS-2024.8.3/lib/python3.12/site-packages/aiohttp/web_app.py", line 537, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/Python-3.12.5/HASS-2024.8.3/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/Python-3.12.5/HASS-2024.8.3/lib/python3.12/site-packages/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/Python-3.12.5/HASS-2024.8.3/lib/python3.12/site-packages/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/Python-3.12.5/HASS-2024.8.3/lib/python3.12/site-packages/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/Python-3.12.5/HASS-2024.8.3/lib/python3.12/site-packages/homeassistant/components/http/ban.py", line 85, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/Python-3.12.5/HASS-2024.8.3/lib/python3.12/site-packages/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/Python-3.12.5/HASS-2024.8.3/lib/python3.12/site-packages/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/Python-3.12.5/HASS-2024.8.3/lib/python3.12/site-packages/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/Python-3.12.5/HASS-2024.8.3/lib/python3.12/site-packages/homeassistant/components/camera/__init__.py", line 813, in get
    return await self.handle(request, camera)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/Python-3.12.5/HASS-2024.8.3/lib/python3.12/site-packages/homeassistant/components/camera/__init__.py", line 831, in handle
    image = await _async_get_image(
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/Python-3.12.5/HASS-2024.8.3/lib/python3.12/site-packages/homeassistant/components/camera/__init__.py", line 185, in _async_get_image
    else await camera.async_camera_image(width=width, height=height)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/Python-3.12.5/HASS-2024.8.3/lib/python3.12/site-packages/homeassistant/components/familyhub/camera.py", line 59, in async_camera_image
    return await self.family_hub_cam.async_get_cam_image()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/Python-3.12.5/HASS-2024.8.3/lib/python3.12/site-packages/pyfamilyhublocal/__init__.py", line 29, in async_get_cam_image
    glazeCameraInfo = await self._get_cam_info()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/Python-3.12.5/HASS-2024.8.3/lib/python3.12/site-packages/pyfamilyhublocal/__init__.py", line 52, in _get_cam_info
    async with async_timeout.timeout(5, loop=self._loop):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: timeout() got an unexpected keyword argument 'loop'
```

Can you check this please? If you need more info, please let me know.

**Comment by pallemannen** [comment]
This repo seems not to be maintained, but the fix is to drop the `loop` parameter from the `async_timeout` call in `__init__.py`.

If you enable [Developer SSH](https://developers.home-assistant.io/docs/operating-system/debugging/#enabling-ssh-access-to-the-host) you can run this:

`sed -i 's/async_timeout.timeout(5, loop=self._loop)/async_timeout.timeout(5)/' /usr/local/lib/python3.14/site-packages/pyfamilyhublocal/__init__.py`

And then restart HA Core.

It will get reverted at every HA Core upgrade, so you will have to run it again each time.

BUT! It doesn't help. This library points at an onsolete endpoint in the API, so it returns a 404.

My suggestion is to use https://github.com/ibielopolskyi/smartthings_fridge_camera instead.
